#include "common.h"
#include "lexer.h"


int main(int argc, char *argv[]) {
    DEBUG_PRINT("Lexer test\n");
    char *source = 
        "/**\n"
        "\tEXAMPLE PROGRAM IN LUKAKOU\n"
        "**/\n"
        "\n"
        "// Variable declarations\n"
        "DECLARE VAR count AS Integer\n"
        "DECLARE VAR message AS String\n"
        "DECLARE VAR numbers AS Array OF Integer = [1, 2, 3, 4, 5]\n"
        "\n"
        "// Function declaration with body\n"
        "DECLARE FUNCTION add WITH (\n"
        "\ta AS Integer, \n"
        "\tb AS Integer\n"
        ") AS Integer\n"
        "BEGIN\n"
        "\tRETURN a + b\n"
        "END\n"
        "\n"
        "// Function to read from stdin and print result if true\n"
        "DECLARE FUNCTION readAndPrint WITH (\n"
        "\tfileDescriptor AS integer,\n"
        "\tprintResult AS boolean\n"
        ") AS string\n"
        "BEGIN\n"
        "\tDECLARE stringRead AS string = \"\"\n"
        "\tREAD FROM fileDescriptor INTO stringRead\n"
        "\n"
        "\tIF printResult IS true THEN\n"
        "\t\tPRINT FROM stringRead INTO stdout\n"
        "\tEND\n"
        "\tRETURN stringRead\n"
        "END\n"
        "\n"
        "// Call the function and assign result to a variable\n"
        "DECLARE result AS string = CALL readAndPrint WITH (stdin, true)\n"
        "\n"
        "// IF/OTHERWISE structure\n"
        "DECLARE VAR var1 AS integer = 0\n"
        "READ FROM stdin INTO var1\n"
        "\n"
        "IF var1 IS 9 THEN\n"
        "\tPRINT FROM \"You win\" INTO stdout\n"
        "OTHERWISE\n"
        "\tPRINT FROM \"You lose\" INTO stdout\n"
        "END\n"
        "\n"
        "// FOR loop\n"
        "DECLARE VAR i AS integer\n"
        "FOR i = 0 UNTIL i GREATER THAN 10 WITH i = i + 1 DO\n"
        "\tPRINT i INTO stdout // Print the value of i\n"
        "END\n"
        "\n"
        "// WHILE loop\n"
        "DECLARE VAR j AS integer = 0\n"
        "WHILE j LESS THAN 10 DO\n"
        "\tPRINT j INTO stdout\n"
        "\tj = j + 1\n"
        "END\n"
        "\n"
        "// FOREACH loop over a string\n"
        "DECLARE VAR sentence AS string = \"Salut les amis !\"\n"
        "FOREACH letter IN sentence DO\n"
        "\tPRINT letter INTO stdout\n"
        "END\n"
        "\n"
        "// FOREACH loop over an array\n"
        "DECLARE VAR list AS array OF integer = [10, 12, 14, 16]\n"
        "FOREACH number IN list DO\n"
        "\tPRINT number INTO stdout\n"
        "END\n"
        "\n"
        "// IFNT structure\n"
        "IFNT var1 IS 9 THEN\n"
        "\tPRINT FROM \"You lost\" INTO stdout\n"
        "END\n"
        "\n"
        "// OTHERIF structure\n"
        "DECLARE VAR var2 AS integer = 0\n"
        "READ FROM stdin INTO var2\n"
        "\n"
        "IF var2 IS 9 THEN\n"
        "\tPRINT FROM \"You win\" INTO stdout\n"
        "OTHERIF var2 IS 8 THEN\n"
        "\tPRINT FROM \"You almost win\" INTO stdout\n"
        "OTHERWISE\n"
        "\tPRINT FROM \"You lose\" INTO stdout\n"
        "END\n"
        "\n"
        "// REPEAT UNTIL structure\n"
        "DECLARE VAR k AS integer = 0\n"
        "REPEAT\n"
        "\tPRINT k INTO stdout\n"
        "\tk = k + 1\n"
        "UNTIL k EQUALS 10\n"
        "\n"
        "// CHECK VALUE structure\n"
        "DECLARE VAR score AS integer = 85\n"
        "CHECK score VALUE\n"
        "\tWHEN score GREATER THAN 90 THEN\n"
        "\t\tPRINT FROM \"Excellent\" INTO stdout\n"
        "\tEND\n"
        "\tWHEN score GREATER THAN 75 THEN\n"
        "\t\tPRINT FROM \"Good\" INTO stdout\n"
        "\tEND\n"
        "\tOTHERWISE\n"
        "\t\tPRINT FROM \"Needs Improvement\" INTO stdout\n"
        "\tEND\n"
        "END\n";
    lexer_t lexer = create_lexer(source, strlen(source));
    token_t token = next_token(&lexer);
    
    while (token.type != TOKEN_EOF) {
        printf("[%s]\t [%.*s]\n", str_token_type(token.type), (int)token.textLen, token.text);
        token = next_token(&lexer);
    }
    
    return EXIT_SUCCESS;
}